from __future__ import annotations

import csv
import re
from collections.abc import Iterator
from pathlib import Path

from logic_mcp.capture.types import Channel, CaptureFormat, FormatInfo, LogicCapture, Snapshot
from logic_mcp.errors import CaptureOpenError

_RATE_RE = re.compile(r"Sample rate:\s*([0-9.]+)\s*([kKmMgG]?)\s*Hz", re.I)
_COUNT_RE = re.compile(r"Sample count:\s*([0-9.]+)\s*([kKmM]?)", re.I)


def _si_multiplier(suffix: str) -> float:
    suffix = suffix.lower()
    return {"": 1.0, "k": 1e3, "m": 1e6, "g": 1e9}[suffix]


def parse_dsview_header(path: Path) -> tuple[list[str], dict[str, str], float | None, int | None, int]:
    metadata: dict[str, str] = {}
    header: list[str] | None = None
    skip = 0
    sample_rate = None
    sample_count = None
    with path.open("r", encoding="utf-8", errors="replace", newline="") as fh:
        for line in fh:
            skip += 1
            stripped = line.strip()
            if stripped.startswith(";"):
                body = stripped[1:].strip()
                metadata[f"comment_{len(metadata)}"] = body
                if "generated by libsigrok4dsl" in body.lower() or "generated by libsigrok" in body.lower():
                    metadata["generator"] = body
                match = _RATE_RE.search(body)
                if match:
                    sample_rate = float(match.group(1)) * _si_multiplier(match.group(2))
                match = _COUNT_RE.search(body)
                if match:
                    sample_count = int(float(match.group(1)) * _si_multiplier(match.group(2)))
                continue
            if not stripped:
                continue
            header = next(csv.reader([stripped]))
            break
    if not header:
        raise CaptureOpenError(f"No CSV header in {path}")
    header = [col.strip() for col in header]
    return header, metadata, sample_rate, sample_count, skip - 1


def _parse_bit(raw: str) -> int:
    raw = raw.strip()
    if raw in ("0", "1"):
        return int(raw)
    try:
        return 1 if float(raw) else 0
    except ValueError as exc:
        raise CaptureOpenError(f"Non-digital CSV value: {raw!r}") from exc


def iter_dsview_csv_snapshots(path: Path, data_width: int, skip_header_lines: int) -> Iterator[Snapshot]:
    """Yield a snapshot only when the digital vector changes (works for raw or compressed CSV)."""
    prev: tuple[int, ...] | None = None
    with path.open("r", encoding="utf-8", errors="replace", newline="") as fh:
        for _ in range(skip_header_lines):
            next(fh, None)
        reader = csv.reader(fh)
        next(reader, None)
        for row in reader:
            if not row or not row[0] or row[0].startswith(";"):
                continue
            if len(row) < 1 + data_width:
                continue
            try:
                t = float(row[0].strip().replace(",", "."))
            except ValueError:
                continue
            values = tuple(_parse_bit(cell) for cell in row[1 : 1 + data_width])
            if values == prev:
                continue
            prev = values
            yield Snapshot(t, values)


class DsviewCsvFormat(CaptureFormat):
    info = FormatInfo(
        id="dsview_csv",
        vendor="DreamSourceLab",
        title="DSView logic CSV (raw or compressed)",
        status="implemented",
        extensions=(".csv",),
        notes="File > Export > CSV from DSView logic analyzer mode. Prefer compressed export.",
    )

    def sniff(self, path: Path) -> float:
        if path.suffix.lower() != ".csv":
            return 0.0
        try:
            with path.open("r", encoding="utf-8", errors="replace") as fh:
                head = "".join(fh.readline() for _ in range(8))
        except OSError:
            return 0.0
        lower = head.lower()
        if "libsigrok4dsl" in lower or "dsview" in lower:
            return 0.95
        if lower.lstrip().startswith(";") and "time(s)" in lower:
            return 0.7
        return 0.0

    def open(self, path: Path) -> LogicCapture:
        header, metadata, rate, count, skip = parse_dsview_header(path)
        if len(header) < 2:
            raise CaptureOpenError("CSV must have a time column and at least one channel")
        time_name, *channel_names = header
        if not time_name.lower().startswith("time"):
            raise CaptureOpenError(f"First CSV column should be time, got {time_name!r}")
        width = len(channel_names)
        channels = [Channel(index=i, name=name) for i, name in enumerate(channel_names)]

        def _iter() -> Iterator[Snapshot]:
            return iter_dsview_csv_snapshots(path, width, skip)

        return LogicCapture(
            info=self.info,
            channels=channels,
            source="file",
            path=path,
            sample_rate_hz=rate,
            sample_count=count,
            metadata=metadata,
            _iter_snapshots=_iter,
        )
