from __future__ import annotations

import json
from pathlib import Path

from PIL import Image

from logic_mcp.bus.i8080 import I8080Decoder
from logic_mcp.capture.dsview_csv import DsviewCsvFormat
from logic_mcp.session import Session
from tests.synth import DEFAULT_MAP, HEADER, rgb565_fill, write_bytes, write_logic_csv

EXAMPLES = Path(__file__).resolve().parents[1] / "examples"
PANEL_INIT = EXAMPLES / "captures" / "panel_init.csv"
CHANNEL_MAP = json.loads(
    (EXAMPLES / "channel_maps" / "i8080_dsview.json").read_text(encoding="utf-8")
)
PANEL_GOLDEN = json.loads(
    (EXAMPLES / "expected" / "panel_init.analyze.json").read_text(encoding="utf-8")
)
FILL_GOLDEN = json.loads(
    (EXAMPLES / "expected" / "fill_red.analyze.json").read_text(encoding="utf-8")
)


def _cmd_key(row: dict) -> tuple:
    return (row["opcode"], row["name"], row["data_len"], row["is_pixel"], row["params"])


def _tiny_fill_red_csv(path: Path, width: int = 4, height: int = 2) -> Path:
    rows: list[list[str]] = []
    t = 0.0
    xe, ye = width - 1, height - 1
    t = write_bytes(rows, t, bytes([0x2A]), dc=0)
    t = write_bytes(rows, t, bytes([0x00, 0x00, 0x00, xe]), dc=1)
    t = write_bytes(rows, t, bytes([0x2B]), dc=0)
    t = write_bytes(rows, t, bytes([0x00, 0x00, 0x00, ye]), dc=1)
    t = write_bytes(rows, t, bytes([0x2C]), dc=0)
    t = write_bytes(rows, t, rgb565_fill(0xF800, width * height), dc=1)
    write_bytes(rows, t, bytes([0x00]), dc=0)
    return write_logic_csv(path, HEADER, rows)


def test_panel_init_is_synthetic():
    text = PANEL_INIT.read_text(encoding="utf-8")
    assert "generated by logic-mcp example" in text
    assert "libsigrok4DSL" not in text


def test_panel_init_dsview_decode():
    capture = DsviewCsvFormat().open(PANEL_INIT)
    assert capture.channel_names == PANEL_GOLDEN["capture"]["channels"]
    assert capture.sample_rate_hz == 100e6
    cycles = list(I8080Decoder().decode(capture, CHANNEL_MAP))
    assert len(cycles) == 17
    wr = [c for c in cycles if c.strobe == "wr"]
    rd = [c for c in cycles if c.strobe == "rd"]
    assert len(wr) == 16
    assert len(rd) == 1
    assert wr[0].extras.get("dc") == 0
    assert wr[0].data == 0x3A
    assert wr[1].extras.get("dc") == 1
    assert wr[1].data == 0x55


def test_panel_init_session_interpret(tmp_path: Path):
    session = Session()
    opened = session.open(str(PANEL_INIT))
    assert opened["ok"]
    assert opened["sample_rate_hz"] == 100e6
    decoded = session.decode("i8080", CHANNEL_MAP)
    assert decoded["event_count"] == 17
    assert decoded["by_kind"]["wr"] == 16
    assert decoded["by_kind"]["rd"] == 1
    analyzed = session.interpret(
        decoder_id="mipi_dcs",
        profile_id="st7789",
        out_dir=str(tmp_path),
    )
    assert analyzed["command_count"] == 6
    assert analyzed["commands"][0]["name"] == "COLMOD"
    names = [row["name"] for row in analyzed["commands"]]
    assert names == ["COLMOD", "SLPOUT", "MADCTL", "CASET", "RASET", "DISPON"]
    live = [_cmd_key(row) for row in analyzed["commands"]]
    expected = [_cmd_key(row) for row in PANEL_GOLDEN["display_analyze"]["commands"]]
    assert live == expected


def test_fill_red_synth_reconstruct(tmp_path: Path):
    width, height = 4, 2
    csv_path = _tiny_fill_red_csv(tmp_path / "fill_red_tiny.csv", width, height)
    session = Session()
    session.open(str(csv_path))
    decoded = session.decode("i8080", DEFAULT_MAP)
    assert decoded["by_kind"]["wr"] == 5 + 5 + 1 + width * height * 2 + 1
    analyzed = session.interpret(
        decoder_id="mipi_dcs",
        profile_id="st7789",
        out_dir=str(tmp_path),
    )
    names = [row["name"] for row in analyzed["commands"]]
    assert names == ["CASET", "RASET", "RAMWR", "NOP"]
    rebuilt = session.reconstruct(
        "st7789",
        width=width,
        height=height,
        save_intermediate_frames=False,
        out_dir=str(tmp_path / "out"),
    )
    assert rebuilt["pixels_written"] == width * height
    assert rebuilt["pixel_overflow"] == 0
    assert rebuilt["ramwr_count"] == 1
    assert rebuilt["window"] == {"xs": 0, "xe": width - 1, "ys": 0, "ye": height - 1}
    image = Image.open(rebuilt["png"]["final"])
    assert image.size == (width, height)
    assert image.getpixel((0, 0)) == (255, 0, 0)
    assert image.getpixel((width - 1, height - 1)) == (255, 0, 0)


def test_reconstructed_pngs():
    fill = Image.open(EXAMPLES / "expected" / "fill_red.png")
    assert fill.size == (240, 320)
    assert fill.getpixel((0, 0)) == (255, 0, 0)
    assert fill.getpixel((239, 319)) == (255, 0, 0)
    init = Image.open(EXAMPLES / "expected" / "panel_init.png")
    assert init.size == (240, 320)
    assert init.getpixel((0, 0)) == (0x30, 0x30, 0x30)


def test_fill_red_golden_documents_full_capture():
    decode = FILL_GOLDEN["bus_decode"]
    assert decode["event_count"] == 153612
    assert decode["by_kind"] == {"wr": 153612}
    commands = FILL_GOLDEN["display_analyze"]["commands"]
    assert [row["name"] for row in commands] == ["CASET", "RASET", "RAMWR", "NOP"]
    assert commands[0]["params"] == ["0x00", "0x00", "0x00", "0xEF"]
    assert commands[1]["params"] == ["0x00", "0x00", "0x01", "0x3F"]
    assert commands[2]["data_len"] == 153600
    assert commands[2]["is_pixel"] is True
    rec = FILL_GOLDEN["display_reconstruct"]
    assert rec["width"] == 240
    assert rec["height"] == 320
    assert rec["pixels_written"] == 76800
    assert rec["pixel_overflow"] == 0
    assert rec["ramwr_count"] == 1
    assert rec["window"] == {"xs": 0, "xe": 239, "ys": 0, "ye": 319}
    assert rec["png"] == "expected/fill_red.png"
