from pathlib import Path

import pytest

from logic_mcp.bus.i8080 import I8080Decoder
from logic_mcp.bus.events import ParallelCycle
from logic_mcp.bus.roles import resolve_channel_map
from logic_mcp.bus.registry import get_bus, list_buses
from logic_mcp.capture.dsview_csv import DsviewCsvFormat
from logic_mcp.capture.stream import edges_from_snapshots, snapshots_from_edges
from logic_mcp.capture.types import Edge, Snapshot
from logic_mcp.errors import ChannelMapError, UnimplementedBusError
from tests.synth import DEFAULT_MAP, build_st7789_blocks_csv


def test_dsview_csv_and_i8080_decode(tmp_path: Path):
    csv_path = build_st7789_blocks_csv(tmp_path / "cap.csv")
    capture = DsviewCsvFormat().open(csv_path)
    assert capture.channel_names[0] == "D0"
    assert capture.sample_rate_hz == 100_000_000
    cycles = list(I8080Decoder().decode(capture, DEFAULT_MAP))
    assert all(isinstance(c, ParallelCycle) for c in cycles)
    writes = [c for c in cycles if c.strobe == "wr"]
    cmds = [c for c in writes if c.extras.get("dc") == 0]
    data = [c for c in writes if c.extras.get("dc") == 1]
    assert cmds[0].data == 0x3A
    assert any(c.data == 0x2C for c in cmds)
    assert len(data) == 1 + 1 + 4 + 4 + 128 + 4 + 4 + 128
    assert data[0].data == 0x05


def test_capture_edges_roundtrip(tmp_path: Path):
    csv_path = build_st7789_blocks_csv(tmp_path / "cap.csv")
    capture = DsviewCsvFormat().open(csv_path)
    snaps = list(capture.iter_snapshots())
    edges = list(capture.iter_edges())
    assert edges
    rebuilt = list(snapshots_from_edges(len(capture.channels), iter(edges)))
    assert [s.values for s in rebuilt] == [s.values for s in snaps]
    from_snaps = list(edges_from_snapshots(iter(snaps)))
    assert from_snaps[0] == Edge(snaps[0].t, 0, snaps[0].values[0])


def test_cs_high_ignores_write(tmp_path: Path):
    csv_path = tmp_path / "idle.csv"
    csv_path.write_text(
        "; CSV, generated by libsigrok4DSL\n"
        "Time(s),D0,D1,D2,D3,D4,D5,D6,D7,CS,DC,WR\n"
        "0,1,0,0,0,0,0,0,0,1,0,0\n"
        "1e-7,1,0,0,0,0,0,0,0,1,0,1\n",
        encoding="utf-8",
    )
    capture = DsviewCsvFormat().open(csv_path)
    mapping = {k: v for k, v in DEFAULT_MAP.items() if k != "rd"}
    cycles = list(I8080Decoder().decode(capture, mapping))
    assert cycles == []


def test_channel_map_index_and_missing():
    names = ["D0", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "CS", "DC", "WR"]
    decoder = I8080Decoder()
    resolved = resolve_channel_map(
        decoder.roles,
        {
            "d0": 0, "d1": 1, "d2": 2, "d3": 3, "d4": 4, "d5": 5, "d6": 6, "d7": 7,
            "cs": 8, "dc": "DC", "wr": "WR",
        },
        names,
    )
    assert resolved["wr"] == 10
    with pytest.raises(ChannelMapError):
        resolve_channel_map(decoder.roles, {"wr": "WR", "dc": "DC"}, names)


def test_spi_not_implemented_but_has_roles():
    decoder = get_bus("spi")
    assert decoder.status == "unimplemented"
    role_names = {r["name"] for r in decoder.roles_dict()}
    assert {"sck", "mosi", "dc"} <= role_names
    with pytest.raises(UnimplementedBusError):
        decoder.decode(None, {})  # type: ignore[arg-type]
    buses = {b["id"]: b for b in list_buses()}
    assert buses["i8080"]["roles"]
    assert "cs_active_low" in buses["i8080"]["options_schema"]["properties"]


def test_snapshots_from_edges_groups_same_timestamp():
    edges = [
        Edge(0.0, 0, 1),
        Edge(0.0, 1, 1),
        Edge(1.0, 0, 0),
    ]
    snaps = list(snapshots_from_edges(2, iter(edges)))
    assert snaps == [
        Snapshot(0.0, (1, 1)),
        Snapshot(1.0, (0, 1)),
    ]
