from __future__ import annotations

from pathlib import Path

HEADER = ["Time(s)", "D0", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "CS", "DC", "WR", "RD"]


def _row(t: float, data: int, cs: int, dc: int, wr: int, rd: int = 1) -> list[str]:
    bits = [(data >> i) & 1 for i in range(8)]
    return [f"{t:.9e}", *[str(b) for b in bits], str(cs), str(dc), str(wr), str(rd)]


def write_bytes(
    rows: list[list[str]],
    t: float,
    payload: bytes,
    dc: int,
    cs: int = 0,
    dt: float = 1e-7,
) -> float:
    for value in payload:
        t += dt
        rows.append(_row(t, value, cs, dc, wr=0))
        t += dt
        rows.append(_row(t, value, cs, dc, wr=1))
    return t


def cmd(opcode: int, *params: int) -> bytes:
    return bytes([opcode, *params])


def rgb565_fill(color: int, count: int) -> bytes:
    hi, lo = (color >> 8) & 0xFF, color & 0xFF
    return bytes([hi, lo] * count)


def write_logic_csv(
    path: Path,
    header: list[str],
    rows: list[list[str]],
    *,
    sample_rate_hz: float = 100_000_000,
    generator: str = "libsigrok4DSL 0.2.0",
) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(f"; CSV, generated by {generator}\n")
        fh.write(f"; Channels ({len(header) - 1})\n")
        rate = int(sample_rate_hz) if float(sample_rate_hz).is_integer() else sample_rate_hz
        fh.write(f"; Sample rate: {rate} Hz\n")
        fh.write(f"; Sample count: {len(rows)}\n")
        fh.write("; Compressed export\n")
        fh.write(",".join(header) + "\n")
        for row in rows:
            fh.write(",".join(row) + "\n")
    return path


def build_st7789_blocks_csv(path: Path, sample_rate_hz: float = 100_000_000) -> Path:
    """Compressed-style DSView CSV: red 8x8 at (2,2), green 8x8 at (12,12)."""
    rows: list[list[str]] = []
    t = 0.0
    rows.append(_row(t, 0, cs=1, dc=0, wr=1, rd=1))
    t = write_bytes(rows, t, bytes([0x3A]), dc=0)
    t = write_bytes(rows, t, bytes([0x05]), dc=1)
    t = write_bytes(rows, t, bytes([0x36]), dc=0)
    t = write_bytes(rows, t, bytes([0x00]), dc=1)
    t = write_bytes(rows, t, bytes([0x2A]), dc=0)
    t = write_bytes(rows, t, bytes([0x00, 0x02, 0x00, 0x09]), dc=1)
    t = write_bytes(rows, t, bytes([0x2B]), dc=0)
    t = write_bytes(rows, t, bytes([0x00, 0x02, 0x00, 0x09]), dc=1)
    t = write_bytes(rows, t, bytes([0x2C]), dc=0)
    t = write_bytes(rows, t, rgb565_fill(0xF800, 64), dc=1)
    t = write_bytes(rows, t, bytes([0x2A]), dc=0)
    t = write_bytes(rows, t, bytes([0x00, 0x0C, 0x00, 0x13]), dc=1)
    t = write_bytes(rows, t, bytes([0x2B]), dc=0)
    t = write_bytes(rows, t, bytes([0x00, 0x0C, 0x00, 0x13]), dc=1)
    t = write_bytes(rows, t, bytes([0x2C]), dc=0)
    write_bytes(rows, t, rgb565_fill(0x07E0, 64), dc=1)
    return write_logic_csv(path, HEADER, rows, sample_rate_hz=sample_rate_hz)


def build_idle_csv(
    path: Path,
    channels: list[str],
    sample_rate_hz: float,
    duration_s: float,
) -> Path:
    header = ["Time(s)", *channels]
    zeros = ["0"] * len(channels)
    rows = [
        ["0.000000000e+00", *zeros],
        [f"{duration_s:.9e}", *zeros],
    ]
    return write_logic_csv(
        path,
        header,
        rows,
        sample_rate_hz=sample_rate_hz,
        generator="logic-mcp mock",
    )


DEFAULT_MAP = {
    "d0": "D0",
    "d1": "D1",
    "d2": "D2",
    "d3": "D3",
    "d4": "D4",
    "d5": "D5",
    "d6": "D6",
    "d7": "D7",
    "cs": "CS",
    "dc": "DC",
    "wr": "WR",
    "rd": "RD",
}


# Probe labels commonly exported from DSView (RS = D/C).
DSVIEW_I8080_HEADER = [
    "Time(s)", "RS", "CS", "RD", "WR",
    "DB0", "DB1", "DB2", "DB3", "DB4", "DB5", "DB6", "DB7",
]
DSVIEW_I8080_MAP = {
    "d0": "DB0", "d1": "DB1", "d2": "DB2", "d3": "DB3",
    "d4": "DB4", "d5": "DB5", "d6": "DB6", "d7": "DB7",
    "wr": "WR", "dc": "RS", "cs": "CS", "rd": "RD",
}


def _row_dsview(t: float, data: int, *, rs: int, cs: int, rd: int, wr: int) -> list[str]:
    bits = [(data >> i) & 1 for i in range(8)]
    return [f"{t:.9e}", str(rs), str(cs), str(rd), str(wr), *[str(b) for b in bits]]


def write_dsview_bytes(
    rows: list[list[str]],
    t: float,
    payload: bytes,
    *,
    rs: int,
    cs: int = 0,
    rd: int = 1,
    dt: float = 1e-7,
) -> float:
    for value in payload:
        t += dt
        rows.append(_row_dsview(t, value, rs=rs, cs=cs, rd=rd, wr=0))
        t += dt
        rows.append(_row_dsview(t, value, rs=rs, cs=cs, rd=rd, wr=1))
    return t


def build_st7789_init_csv(path: Path, sample_rate_hz: float = 100_000_000) -> Path:
    """Synthetic ST7789 init (datasheet-style). Not a dump from a particular board."""
    rows: list[list[str]] = []
    t = 0.0
    rows.append(_row_dsview(t, 0, rs=1, cs=1, rd=1, wr=1))
    t += 1e-7
    rows.append(_row_dsview(t, 0, rs=1, cs=0, rd=0, wr=1))
    t += 1e-7
    rows.append(_row_dsview(t, 0, rs=1, cs=0, rd=1, wr=1))
    t = write_dsview_bytes(rows, t, bytes([0x3A]), rs=0)
    t = write_dsview_bytes(rows, t, bytes([0x55]), rs=1)
    t = write_dsview_bytes(rows, t, bytes([0x11]), rs=0)
    t = write_dsview_bytes(rows, t, bytes([0x36]), rs=0)
    t = write_dsview_bytes(rows, t, bytes([0x00]), rs=1)
    t = write_dsview_bytes(rows, t, bytes([0x2A]), rs=0)
    t = write_dsview_bytes(rows, t, bytes([0x00, 0x00, 0x00, 0xEF]), rs=1)
    t = write_dsview_bytes(rows, t, bytes([0x2B]), rs=0)
    t = write_dsview_bytes(rows, t, bytes([0x00, 0x00, 0x01, 0x3F]), rs=1)
    write_dsview_bytes(rows, t, bytes([0x29]), rs=0)
    return write_logic_csv(
        path,
        DSVIEW_I8080_HEADER,
        rows,
        sample_rate_hz=sample_rate_hz,
        generator="logic-mcp example",
    )
